tasks:
  - name: shopback.com.au
    init: pip install -r requirements.txt 
    command: sudo apt-get update && apt-get install -y libsm6 libxext6 libxrender1 libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*
